return {
  opt = {
    relativenumber = true,
    number = true,
    spell = false,
    signcolumn = "yes",
    wrap = true,
    scrolloff = 8,
    swapfile = false,
    backup = false,
    undodir = os.getenv "HOME" .. "/.cache/nvim/undodir",
    undofile = true,
    hlsearch = false,
    incsearch = true,
    completeopt = "menu,menuone,noselect,popup",
    autoindent = true,
    smartindent = true,
    cindent = false,
  },
}
